name = "RPG24"
author = "Hathfury"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a14d9e46a029ab63f72827c365456370352e3374bca9fa5d1b98cf10c27d1dce"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
