name = "RPG24"
author = "Hathfury"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4982543ef6deb47ab6b6f9de72a32c5ae91ff2256f9d7c2ed60b6646eb5b5ccf"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
