name = "RPG24"
author = "Hathfury"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c6317c5541cc3580f482a39f6c6a8e70e229d2ab9a9a312a1d70a46a463c2db8"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
