name = "RPG24"
author = "Hathfury"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cedddf64fc2f8fd807e1d95a5032943aa239467d287ec02d21a7f6229e768baa"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
