name = "RPG24"
author = "Hathfury"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f5f7a482b21cff1ebdf037f78e98b2ff5242937451bd7f4ad0f9bf2f42b241e2"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
