name = "RPG24"
author = "Hathfury"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c035b7a9f1cbb15202f90f50fef555afc4d151b38e6eda7b370ea8b6f5482ad6"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
